BeautyMe/Controllers/ServicosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BeautyMe.Models;

namespace BeautyMe.Controllers
{
    public class ServicosController : Controller
    {
        private Contexto _contexto = new Contexto();

        // GET: Servicos
        [Authorize]
        public ActionResult Index()
        {
            var servicos = _contexto.ServicosEntities.ToList().Where(a => a.Profissional.Email == User.Identity.Name && a.Desativado==false);
            return View(servicos);
        }

        // GET: Servicos/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Servico servico = _contexto.ServicosEntities.Find(id);
            if (servico == null)
            {
                return HttpNotFound();
            }
            return View(servico);
        }

        // GET: Servicos/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Servicos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "Id,Name,Descricao,Preco,Tempo")] Servico servico)
        {
            if (ModelState.IsValid)
            {
                servico.Profissional = _contexto.ProfissionalEntities.ToList().Find(a => a.Email == User.Identity.Name);
                _contexto.ServicosEntities.Add(servico);
                _contexto.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(servico);
        }

        // GET: Servicos/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Servico servico = _contexto.ServicosEntities.Find(id);
            if (servico == null)
            {
                return HttpNotFound();
            }
            return View(servico);
        }

        // POST: Servicos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(Servico servico)
        {
            
            if (ModelState.IsValid)
            {
                var serv = _contexto.ServicosEntities.ToList().Find(a => a.Id == servico.Id);
                serv.Name = servico.Name;
                serv.Preco = servico.Preco;
                serv.Descricao = servico.Descricao;
                serv.Tempo = servico.Tempo;
                
                _contexto.Entry(serv).State = EntityState.Modified;
                _contexto.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(servico);
        }

        // GET: Servicos/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Servico servico = _contexto.ServicosEntities.Find(id);
            if (servico == null)
            {
                return HttpNotFound();
            }
            servico.Desativado = !servico.Desativado;
            _contexto.Entry(servico).State = EntityState.Modified;
            _contexto.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Servicos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Servico servico = _contexto.ServicosEntities.Find(id);
            _contexto.ServicosEntities.Remove(servico);
            _contexto.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Pesquisar(string pesquisa = "")
        {
            return View(_contexto.ServicosEntities.ToList().Where(p => p.Name.Contains(pesquisa)&& p.Desativado == false).ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _contexto.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BeautyMe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery.js"></script>
    <script>
        window.onload = function(e) {
            const redirectPage = 'Home/OnlyMobile'
            const isMobile = window.matchMedia && window.matchMedia('(max-width: 800px)').matches;
            if (!isMobile) window.location.pathname = redirectPage;
        }

    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Beauty&Me", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Agenda", "Index", "Agenda")</li>
                        <li>@Html.ActionLink("Pesquisar", "Pesquisar", "Servicos")</li>
                    }
                    @if (User.IsInRole("Profissional"))
                    {
                        <li>@Html.ActionLink("Serviços", "Index", "Servicos")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
	@Scripts.Render("~/Scripts/jquery.js")
	@Scripts.Render("~/Scripts/responsive-calendar.js")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>